package com.atguigu.atcrowdfunding.bean;

public class Advert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.id
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.name
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.iconpath
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    private String iconpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.status
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.url
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_advertisement.userid
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    private Integer userid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.id
     *
     * @return the value of t_advertisement.id
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.id
     *
     * @param id the value for t_advertisement.id
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.name
     *
     * @return the value of t_advertisement.name
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.name
     *
     * @param name the value for t_advertisement.name
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.iconpath
     *
     * @return the value of t_advertisement.iconpath
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public String getIconpath() {
        return iconpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.iconpath
     *
     * @param iconpath the value for t_advertisement.iconpath
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public void setIconpath(String iconpath) {
        this.iconpath = iconpath == null ? null : iconpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.status
     *
     * @return the value of t_advertisement.status
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.status
     *
     * @param status the value for t_advertisement.status
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.url
     *
     * @return the value of t_advertisement.url
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.url
     *
     * @param url the value for t_advertisement.url
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_advertisement.userid
     *
     * @return the value of t_advertisement.userid
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_advertisement.userid
     *
     * @param userid the value for t_advertisement.userid
     *
     * @mbggenerated Fri Dec 22 18:26:56 CST 2017
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }
}