package com.atguigu.atcrowdfunding.bean;

public class Cert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cert.id
     *
     * @mbggenerated Sat Dec 16 17:29:36 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_cert.name
     *
     * @mbggenerated Sat Dec 16 17:29:36 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cert.id
     *
     * @return the value of t_cert.id
     *
     * @mbggenerated Sat Dec 16 17:29:36 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cert.id
     *
     * @param id the value for t_cert.id
     *
     * @mbggenerated Sat Dec 16 17:29:36 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_cert.name
     *
     * @return the value of t_cert.name
     *
     * @mbggenerated Sat Dec 16 17:29:36 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_cert.name
     *
     * @param name the value for t_cert.name
     *
     * @mbggenerated Sat Dec 16 17:29:36 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}